streaming scripts

diff --git a/ffmpeg/start b/ffmpeg/start
--- a/ffmpeg/start
+++ b/ffmpeg/start
@@ -1,1 +1,22 @@
-ffmpeg -f jack -i ffmpeg -y ./ffmpeg/out.wav
+#!/bin/bash
+echo killing old ffmpegs
+
+PID=( $(ps -e | grep ffmpeg | awk '{print $1;}'))
+if [ $? = 1 ];then
+echo "error getting ffmpeg PID, exiting"
+exit
+fi
+if [ ! -n "$PID" ];then
+PID=1234567
+fi
+echo killing ffmpeg with PID $PID
+kill $PID
+
+echo starting ffmpeg
+#ffmpeg -re -f jack -i ffmpeg -acodec ogg -ab 32k -ac 1 -f rtp rtp://192.168.0.254:1234
+ffmpeg -f jack -i ffmpeg -f rtp rtp://127.0.0.1:1234  > ffmpeg/stream.sdp
+
+FF=$!
+echo ffmpeg started with PID $FF
+
+exit
diff --git a/puredata/start b/puredata/start
--- a/puredata/start
+++ b/puredata/start
@@ -1,1 +1,21 @@
-pd -stderr -jack -inchannels 2 -r 44100 -send ";\pd dsp 1" ./puredata/patch.pd
+#!/bin/bash
+echo killing old pd
+
+PID=( $(ps -e | grep pd | awk '{print $1;}'))
+if [ $? = 1 ];then
+echo "error getting pd PID, exiting"
+exit
+fi
+if [ ! -n "$PID" ];then
+PID=1234567
+fi
+echo killing pd with PID $PID
+kill $PID
+
+echo starting pd
+pd -jack -inchannels 2 -r 44100 -send ";\pd dsp 1" ./puredata/patch.pd
+
+FF=$!
+echo puredata started with PID $FF
+
+exit
diff --git a/stop b/stop
--- a/stop
+++ b/stop
@@ -1,4 +1,21 @@
-./puredata/stop
-./ffmpeg/stop
-./ffserver/stop
-./jack/stop
+#!/bin/bash
+#
+#kill ffmpeg
+echo killing old ffmpegs
+
+PID=( $(ps -e | grep ffmpeg | awk '{print $1;}'))
+if [ $? = 1 ];then
+echo "error getting ffmpeg PID, exiting"
+exit
+fi
+if [ ! -n "$PID" ];then
+PID=1234567
+fi
+echo killing ffmpeg with PID $PID
+kill $PID
+
+#kill pd
+echo killing old pd
+killall pd
+
+exit
